"""Render dependency-graph.json as deterministic Markdown and Mermaid."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
GRAPH_PATH = REPOSITORY_ROOT / "dependency-graph.json"
OUTPUT_PATH = REPOSITORY_ROOT / "docs/generated/dependency-graph.md"


def _node_id(value: str) -> str:
    return value.replace("-", "_")


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render(graph: dict[str, Any]) -> str:
    lines = [
        "# Generated dependency graph",
        "",
        "Generated from `dependency-graph.json`; do not edit this file manually.",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for node in graph["nodes"]:
        lines.append(f'    {_node_id(node)}["{node}"]')
    for edge in graph["allowed_edges"]:
        lines.append(
            f'    {_node_id(edge["from"])} -->|"{edge["type"]}"| {_node_id(edge["to"])}'
        )
    lines.extend(
        [
            "```",
            "",
            "## Allowed dependencies",
            "",
            "| From | To | Type | Rationale |",
            "| --- | --- | --- | --- |",
        ]
    )
    for edge in graph["allowed_edges"]:
        lines.append(
            f'| {_cell(edge["from"])} | {_cell(edge["to"])} | '
            f'{_cell(edge["type"])} | {_cell(edge["rationale"])} |'
        )
    lines.extend(
        [
            "",
            "## Forbidden dependencies",
            "",
            "| From | To | Reason |",
            "| --- | --- | --- |",
        ]
    )
    for edge in graph["forbidden_edges"]:
        lines.append(
            f'| {_cell(edge["from"])} | {_cell(edge["to"])} | {_cell(edge["reason"])} |'
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    with GRAPH_PATH.open(encoding="utf-8") as graph_file:
        graph = json.load(graph_file)
    expected = render(graph)

    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print("[FAIL] Generated dependency graph is stale.", file=sys.stderr)
            return 1
        print("[OK] Generated dependency graph is current.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"[OK] Wrote {OUTPUT_PATH.relative_to(REPOSITORY_ROOT).as_posix()}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
